name: "Upload to Binary Cache and Integration Test"
on:
  push:
  pull_request:
    types: [opened]
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v12
      with:
        name: timhae-firefly
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
    - run: nix flake check
