name: "test"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build-and-check:
    strategy:
      matrix:
        os: [buildjet-2vcpu-ubuntu-2204-arm, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - uses: cachix/cachix-action@6a9a34cdd93d0ae4b4b59fd678660efb08109f2f
        with:
          name: timhae-firefly
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build
      - run: nix flake check
