name: "update"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake update
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(deps): update flake inputs"
          title: "chore(deps): update flake inputs"
          branch: flake-updates
          delete-branch: true
