name: "update"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake update
      - uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          commit-message: "chore(deps): update flake inputs"
          title: "chore(deps): update flake inputs"
          branch: flake-updates
          delete-branch: true
